name: image_repository
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  cloud_firestore: ^1.0.5
  firebase_core: ^1.0.3
  sqflite: ^1.3.2+3
  firebase_storage: ^8.0.3
